### ISSUE TITLE
Should the NUnit project loader be internal?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-project-loader#16]
Currently, the engine has two "internal" extensions. That is, they are coded as if they were extensions but are actually built into the engine itself and are always available.

Those two are the NUnit 3 framework driver and the NUnit 3 result writer.

I'm wondering if the NUnit project loader should be implemented in the same way.

Pros: 
Always available without loading an extension.
One less extension to manage, release and version.

Cons:
Change in behavior but arguably not breaking.

@ChrisMaddock @rprouse @immeraufdemhund @jnm2 @mikkelbu  What do you think?

If this idea has legs, I'll do a final release of the extension and create a PR for the engine. I'd like to see this decided before I do any work on making this extension work in the .NET Core environment.

**Comment by rprouse** [comment]
I don't have a strong opinion on this. My only concern with pulling it into the engine itself is that I don't think it is used as much as it used to be and hasn't seen much work whereas the framework driver and writer are core.

**Comment by ChrisMaddock** [comment]
I disagree with incorporating this extension into the engine.

I think NUnit project files are a great example of a niche piece of functionality, which should be available for advanced users to pull in if required, but causing additional maintenance for the engine itself. We've also talked before about the NUnit Project format possibly becoming legacy and us wanting to replace it with something which better covers the possibilities of the NUnit 3 package structure and options. I wouldn't want us to further embed this format, and then start work on it's replacement in the coming years.

Re: one less extension to manage: if I was the maintainer of this project, I'd want it to be in 'maintenance mode only', with hopefully very limited maintenance required. That said - I'm not the maintainer of this project, and I think that direction lies with you Charlie! 😁

**Comment by CharliePoole** [comment]
In that case, I'll hold on this. We may decide to enhance rather than replace, of course. That said, if we end up creating a new format, I think it should either be built-in or __not__ have the name "nunit" in it's extension. I believe it's by calling it `.nunit` that we've confused so many users over the years. It sounds as if it should be built in!

**Comment by CharliePoole** [comment]
Nothing to do here - that is, if we do anything in the future it will be a new issue.
