### ISSUE TITLE
NuGet description incorrect for project loader

### ISSUE THREAD

**Issue by ketchup201** [nunit/nunit-project-loader#54]
I know this is petty, but the NuGet description that appears for NUnit.Extension.NUnitProjectLoader v3.7.1 is incorrect.

Expected: NUnit engine extension that allows running NUnit projects which have a file extension of .nunit.
Actual Result: NUnit Engine extension for writing test result files in NUnit V2 format.

**Comment by OsirisTerje** [comment]
I'll move this to the correct repository.
Feel free to raise a PR for this :-)

**Comment by OsirisTerje** [comment]
Feel free to raise a PR

**Comment by CharliePoole** [comment]
This is definitely a bug. Probably caused by copy/pasting the descriptions from the V2 Result Writer extension.

Note that nothing can be changed directly on nuget.org without uploading a new version, so even when this is fixed it won't change on nuget.org until we publish a new release.

**Comment by CharliePoole** [comment]
Related to this, this [GitHub Release Description](https://github.com/nunit/nunit-project-loader/releases) has the wrong extension names listed in the text. That could be fixed immediately in the release itself but might be present in the script that generates releases as well.
