### ISSUE TITLE
Rename main branch to version4 and create a new main based on the 3.7.1 tag

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-project-loader#56]
As discussed in #55.

This is a significant change with respect to those working on the extension, but has no impact on users. Fortunately (?) the number of folks working on the code is quite small. 

I'll do this as follows...

~~1. Rename main in the GitHub Ide
2. Update the remotes on my own machine, sync with the new version4 and build
3. Create a new local main branch based on tag 3.7.1 and build that.
4. Push the new main~~

~~This ought to be recoverable at each step. The old main will disappear for a very short time.~~

UPDATED below.

**Comment by CharliePoole** [comment]
@OsirisTerje Although we discussed my doing this, it turns out that GitHub won't let me change the default branch or rename it. So my new plan is to do what I'm able to do and leave the rest till you're back from your trip...

1. Create a local version3 branch based on tag 3.7.1. Cherry-pick changes from #55 needed to make it build. [DONE]
2. Push that branch to GitHub and let it build [DONE]
3. Modify the branch so that version3 acts like main, creating a myget release and push that change.
4. Do a PR on #55 and merge that into version3.

That will leave us with a version3 branch for new release and a main for v4 development, just as we now have for the console/engine repository. We can figure out how and when to make the name changes when you are available.

The above may even be better as it should allow you to change names right in the IDE without any significant time period where there's no main.

Since we know that the other extensions will need separate v3 branches, I'll do the same for them as I get time.

**Comment by CharliePoole** [comment]
@OsirisTerje Stuck again! I previously removed my authorizations from the NUnit MyGet feeds. I have other things I'm working on so we can wait till you are free. Or you could try retriggering a build of my last commit on AppVeyor under your own ID.

**Comment by OsirisTerje** [comment]
@CharliePoole There already is a version3 branch on the remote.  Do you want me to rename main to version4 and then version3 to main ?  No cherry picks (not sure what that should be btw).

**Comment by CharliePoole** [comment]
@OsirisTerje Yes please! it's the 3.7.1 tag plus a few commits to make it build again. GitVersion.yml will need to be changed so that main + version4 go to Myget rather than main + version3. I can do that as part of my first merge.

**Comment by OsirisTerje** [comment]
@CharliePoole   Done!
