### ISSUE TITLE
Integrate Chocolatey package in release build script

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-project-loader#8]
A Chocolatey package now exists for the extension, having been created using the binaries from the 3.5 release. See nunit/nunit-console#253.

We want the creation of the chocolatey package to be integrated with the build such that...
1. It is created whenever we build master after a merge, using the just-built binaries at their version
2. It can be re-created, as needed, __without__ rebuilding the binaries using a script option that points to the binaries to be used and a specified version.

The initial assumption is that the build script will call a separate script that implements (2) passing the location of the binaries and the version.

@core-team Do you agree with this approach? My plan is to use it for this package first, complete a PR and then replicate the same thing for each extension project.

BTW I think it would be great if both points above also applied to NuGet package creation.

**Comment by rprouse** [comment]
Will the packaging be called from the Cake build script and be a dependent task of the overall Package task so that we can produce the packages when we do releases, or will it be a separate release process?

**Comment by CharliePoole** [comment]
I see it as one of the package tasks. I'm not sure if we should do it for PRs though.

**Comment by ChrisMaddock** [comment]
I see no reason why this shouldn't be done on PRs and uploaded as Appveyor artifacts, as the NuGet packages currently are. It's an extra level of security, at no cost to us.

**Comment by CharliePoole** [comment]
My hesitancy is that there will be two nupkgs created and the user may not know which is which. However, if the naming problem can be resolved once I do a PR, then it will be OK.

**Comment by CharliePoole** [comment]
A thought... I'm naming the nuspec files for chocolatey, e.g.: `nunit-project-loader.choco.nuspec` so it's clear when editing which is which. Assuming that chocolatey.org doesn't actually care about the file name we upload, I could rename the `.nupkg` files the same way. I'll give it a try.
